manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.1.0
      west-commands: scripts/west-commands.yml
      import:
        path-prefix: deps/zephyr
        name-allowlist:
          - cmsis
          - hal_nordic
          - hal_stm32
